#!/usr/bin/env bash
#
# Interactive setup for local code signing. Writes an untracked
# scripts/signing.env that package-app.sh sources. This is all you need to build
# and run Footswitch locally with a stable "Apple Development" identity (so the
# Accessibility grant persists).
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SIGNING_ENV="$ROOT/scripts/signing.env"

echo "Footswitch local signing setup"
echo "=============================="
echo

# --- Pick an Apple Development identity from the keychain -------------------

mapfile -t IDENTITIES < <(
  security find-identity -v -p codesigning 2>/dev/null \
    | sed -n 's/.*"\(Apple Development: [^"]*\)".*/\1/p'
)

if [ "${#IDENTITIES[@]}" -eq 0 ]; then
  echo "No 'Apple Development' signing identities found in your keychain." >&2
  echo "Create one in Xcode (Settings -> Accounts -> Manage Certificates -> +)," >&2
  echo "then re-run this script." >&2
  exit 1
fi

echo "Available 'Apple Development' identities:"
for i in "${!IDENTITIES[@]}"; do
  printf "  %d) %s\n" "$((i + 1))" "${IDENTITIES[$i]}"
done
echo

SIGN_IDENTITY=""
if [ "${#IDENTITIES[@]}" -eq 1 ]; then
  SIGN_IDENTITY="${IDENTITIES[0]}"
  echo "Using the only identity found:"
  echo "  $SIGN_IDENTITY"
else
  read -r -p "Choose an identity [1-${#IDENTITIES[@]}]: " choice
  if ! [[ "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt "${#IDENTITIES[@]}" ]; then
    echo "Invalid choice." >&2
    exit 1
  fi
  SIGN_IDENTITY="${IDENTITIES[$((choice - 1))]}"
fi
echo

# --- Write the env file -----------------------------------------------------

umask 077  # signing.env references your signing identity; keep it user-only.
{
  echo "# Local signing config for Footswitch — generated by scripts/setup-signing.sh."
  echo "# Untracked (see .gitignore). Safe to edit by hand."
  echo
  echo "# Apple Development identity used by package-app.sh for local builds."
  echo "SIGN_IDENTITY=\"$SIGN_IDENTITY\""
} > "$SIGNING_ENV"

echo "Wrote $SIGNING_ENV:"
echo
sed 's/^/  /' "$SIGNING_ENV"
echo
echo "You can now run scripts/package-app.sh to build and sign locally."
